#undef TAPPING_FORCE_HOLD
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY

#define RGBLIGHT_LAYERS

#define OLED_BRIGHTNESS 128
#define OLED_UPDATE_INTERVAL 100
#define OLED_TIMEOUT 60000
#define OLED_SCROLL_TIMEOUT 20000

#define NO_ACTION_ONESHOT
#define LAYER_STATE_8BIT
